# Generated by Django 3.0.3 on 2020-07-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='list_read',
        ),
        migrations.AddField(
            model_name='readinglist',
            name='list_read',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='list_read_novel', to='index.Novel'),
        ),
    ]
