# Generated by Django 3.0.3 on 2020-07-20 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200719_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='user_novel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_novels', to='index.UserNovel'),
        ),
    ]
