# Generated by Django 3.0.3 on 2020-07-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_novel_user_novel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernovel',
            name='rol_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rol_users', to='index.RolUser'),
        ),
    ]
